### ISSUE TITLE
Error in the identengine handler for nicks

### ISSUE THREAD

**Issue by optimumtact** [optimumtact/simplepybot#6]
bot ERROR Error in module event handler: identengine
Traceback (most recent call last):
  File "commandbot.py", line 242, in handle_event
    if event(m_event):
  File "/home/oranges/simplepybot/event_util.py", line 38, in process
    func(*message.data)
  File "/home/oranges/simplepybot/modules/identengine.py", line 176, in user_quit
    self.delete_user(nickhost)
  File "/home/oranges/simplepybot/modules/identengine.py", line 56, in delete_user
    del self.nickmap[nick]
NameError: name 'nick' is not defined

**Comment by optimumtact** [comment]
bot.network INFO << brbot!brbot@user/brbot JOIN ['#channel'] None
bot ERROR Error in module event handler: identengine
Traceback (most recent call last):
  File "commandbot.py", line 242, in handle_event
    if event(m_event):
  File "/home/oranges/simplepybot/event_util.py", line 38, in process
    func(*message.data)
  File "/home/oranges/simplepybot/modules/identengine.py", line 176, in user_quit
    self.delete_user(nickhost)
  File "/home/oranges/simplepybot/modules/identengine.py", line 56, in delete_user
    del self.nickmap[nick]
NameError: name 'nick' is not defined
